import { useMemo, useState } from "react";
import { CalendarClock, Check, ChevronDown, Copy, ExternalLink, Mail, MessageSquare, PhoneCall, Send, SkipForward } from "lucide-react";
import { recruiters, RecruiterStatus } from "./recruiterData";

type State = {status:RecruiterStatus; draft:string; lastContact:string; follow1:string; follow2:string; reply?:"positive"|"neutral"|"decline"};
const addBusinessDays=(iso:string,days:number)=>{const d=new Date(`${iso}T12:00:00`);for(let i=0;i<days;){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)i++}return d.toISOString().slice(0,10)};
const message=(name:string,focus:string,opening:string)=>`Hi ${name.split(" ")[0]} — I’m planning a move to Seattle and am targeting Seattle-hybrid or remote data, analytics, and automation roles. I currently work as a Marketing Analyst through TEKsystems and have independently built production systems including Lander, a multi-source labor-market data platform, and Wyloc, an AI data-security product.\n\nMy strongest areas are SQL, Python, PostgreSQL, data pipelines, BI, workflow automation, and applied AI. I’m open to contract, contract-to-hire, or direct hire, targeting $80K+ or approximately $40+/hour. Your work in ${focus.toLowerCase()}—including ${opening.toLowerCase()}—looked especially relevant.\n\nWould you be open to a short call or adding me to your active candidate pool? I can share my résumé and verified project links.`;
const connection=(name:string,focus:string)=>`Hi ${name.split(" ")[0]} — I’m moving to Seattle and targeting hybrid/remote data, analytics, and automation roles. I build production SQL/Python systems and currently contract through TEKsystems. Your ${focus.toLowerCase()} desk looks relevant; open to connecting?`;
const load=():Record<number,State>=>{try{return JSON.parse(localStorage.getItem("recruiter-sprint-state")||"{}")}catch{return {}}};
const initialState=(id:number):State=>{const r=recruiters.find(x=>x.id===id)!;return {status:"ready",draft:message(r.name,r.focus,r.opening),lastContact:"",follow1:"",follow2:""}};

export function RecruiterSprint(){
 const [state,setState]=useState<Record<number,State>>(load); const [selected,setSelected]=useState(1); const [segment,setSegment]=useState("All"); const [links,setLinks]=useState<Record<string,string>>(()=>{try{return JSON.parse(localStorage.getItem("recruiter-packet-links")||"{}")}catch{return {}}});
 const update=(id:number,patch:Partial<State>)=>setState(old=>{const next={...old,[id]:{...initialState(id),...old[id],...patch}};localStorage.setItem("recruiter-sprint-state",JSON.stringify(next));return next});
 const filtered=useMemo(()=>recruiters.filter(r=>segment==="All"||r.segment===segment).sort((a,b)=>b.priority-a.priority),[segment]);
 const current=recruiters.find(r=>r.id===selected)||recruiters[0]; const currentState=state[current.id]||initialState(current.id);
 const today=new Date().toISOString().slice(0,10); const initial=recruiters.slice().sort((a,b)=>b.priority-a.priority).filter(r=>!["contacted","replied","call booked","submitted","inactive"].includes(state[r.id]?.status||"ready")).slice(0,5);
 const metrics={contacts:Object.values(state).filter(x=>["contacted","replied","call booked","submitted"].includes(x.status)).length,replies:Object.values(state).filter(x=>["replied","call booked","submitted"].includes(x.status)).length,calls:Object.values(state).filter(x=>x.status==="call booked").length,submissions:Object.values(state).filter(x=>x.status==="submitted").length};
 const setLink=(key:string,value:string)=>{const next={...links,[key]:value};setLinks(next);localStorage.setItem("recruiter-packet-links",JSON.stringify(next))};
 const mailto=current.email?`mailto:${current.email}?subject=${encodeURIComponent("Seattle data / analytics candidate — Luke")}&body=${encodeURIComponent(currentState.draft)}`:"";
 return <div className="page recruiter-sprint">
  <div className="sprint-hero"><div><span>Approval-only campaign</span><h2>Seattle recruiter sprint</h2><p>40 verified recruiter leads · $80K+ / $40+ hourly · contract, C2H, or direct hire</p></div><div className="sprint-metrics"><b>{metrics.contacts}<small>contacts</small></b><b>{metrics.replies}<small>replies</small></b><b>{metrics.calls}<small>calls</small></b><b>{metrics.submissions}<small>submissions</small></b><b>0<small>interviews</small></b><b>0<small>offers</small></b></div></div>
  <section className="card queue-card"><div className="card-head"><div><span>Today · five initial contacts</span><h3>Approval queue</h3></div></div><div className="daily-queue">{initial.map((r,i)=><button key={r.id} onClick={()=>setSelected(r.id)} className={selected===r.id?"active":""}><i>{i+1}</i><span><b>{r.name}</b><small>{r.firm} · {r.priority}</small></span><ChevronDown/></button>)}</div></section>
  <div className="sprint-layout"><section className="card recruiter-table-card"><div className="sprint-filters">{["All","Seattle / PNW","National remote","Contract / C2H"].map(x=><button className={segment===x?"active":""} onClick={()=>setSegment(x)} key={x}>{x}</button>)}</div><div className="recruiter-table">{filtered.map(r=>{const s=state[r.id]?.status||"ready";return <button key={r.id} onClick={()=>setSelected(r.id)} className={selected===r.id?"selected":""}><strong>{r.priority}</strong><span><b>{r.name}</b><small>{r.firm} · {r.segment}</small></span><em>{s}</em></button>})}</div></section>
   <section className="card recruiter-detail"><div className="recruiter-title"><div><span>Priority {current.priority} · {current.segment}</span><h3>{current.name}</h3><p>{current.title} · {current.firm}</p></div><div><a href={current.linkedin} target="_blank" rel="noreferrer"><ExternalLink/>LinkedIn</a>{current.email&&<a href={mailto}><Mail/>Email</a>}</div></div><dl><div><dt>Recruiting focus</dt><dd>{current.focus}</dd></div><div><dt>Active evidence</dt><dd>{current.evidence} <a href={current.evidenceUrl} target="_blank" rel="noreferrer">Source</a></dd></div><div><dt>Relevant opening</dt><dd><a href={current.openingUrl} target="_blank" rel="noreferrer">{current.opening}</a></dd></div><div><dt>Why Luke matches</dt><dd>{current.match}</dd></div><div><dt>Resume variant</dt><dd>{current.resume}</dd></div><div><dt>Channel</dt><dd>{current.channel}{current.email?` · ${current.email}`:" · no verified public email"}</dd></div></dl>
    <label className="draft-label">Personalized {current.channel} draft<textarea value={currentState.draft} onChange={e=>update(current.id,{draft:e.target.value})}/></label><p className="connection-copy"><b>Connection request ({connection(current.name,current.focus).length}/300)</b>{connection(current.name,current.focus)}</p>
    <div className="contact-actions"><button onClick={()=>navigator.clipboard.writeText(currentState.draft)}><Copy/>Copy</button><button onClick={()=>update(current.id,{status:"approved"})}><Check/>Approve</button><button onClick={()=>update(current.id,{status:"inactive"})}><SkipForward/>Skip</button><button onClick={()=>update(current.id,{status:"contacted",lastContact:today,follow1:addBusinessDays(today,5),follow2:addBusinessDays(addBusinessDays(today,5),7)})}><Send/>Mark sent</button><button onClick={()=>update(current.id,{status:"replied",reply:"positive"})}><MessageSquare/>Replied</button><button onClick={()=>update(current.id,{status:"call booked"})}><PhoneCall/>Call booked</button><button onClick={()=>update(current.id,{status:"submitted"})}>Submitted</button></div>
    {currentState.lastContact&&<div className="followups"><CalendarClock/><span>Sent {currentState.lastContact}</span><span>Follow up {currentState.follow1}</span><span>Final {currentState.follow2}</span></div>}
   </section></div>
  <div className="packet-grid"><section className="card"><div className="card-head"><div><span>Recruiter packet</span><h3>Verified candidate summary</h3></div></div><p className="packet-summary">Marketing Analyst currently working through TEKsystems at AMC who builds production data and automation systems—not only dashboards. Built Lander, a labor-market platform spanning multiple ATS ecosystems, and Wyloc, an AI data-security product. Hands-on with SQL, Python, PostgreSQL, dbt, FastAPI, semantic matching, DigitalOcean infrastructure, workflow automation, BI, data pipelines, and applied AI. Targeting Seattle-area hybrid or genuinely remote data, analytics, automation, applied-AI, technical business-analysis, implementation, or solutions roles. Open to contract, contract-to-hire, and direct hire; able to relocate promptly.</p><ul className="capabilities"><li>SQL, Python, PostgreSQL and production data pipelines</li><li>dbt analytics engineering and BI-ready data models</li><li>FastAPI services and workflow automation</li><li>Semantic matching and applied-AI product systems</li><li>DigitalOcean deployment and production infrastructure</li><li>Technical analysis, implementation and cross-system integration</li></ul><p><b>Compensation & availability:</b> Targeting $80,000+ salary or approximately $40+/hour. Open to contract, contract-to-hire, or direct hire. Planning a Seattle move and can relocate promptly for the right offer.</p></section>
   <section className="card"><div className="card-head"><div><span>Links</span><h3>Add verified destinations</h3></div></div><p className="link-warning">The repository had no verified personal URLs. Add them here on-device; they remain in this browser only.</p>{["LinkedIn","GitHub","Lander","Wyloc"].map(k=><label className="packet-link" key={k}>{k}<input type="url" value={links[k]||""} onChange={e=>setLink(k,e.target.value)} placeholder={`Paste ${k} URL`}/>{links[k]&&<a href={links[k]} target="_blank" rel="noreferrer"><ExternalLink/></a>}</label>)}<div className="spoken"><b>30-second introduction</b><p>I’m a Marketing Analyst working through TEKsystems, but the through-line in my work is building production data and automation systems. I’ve built Lander across multiple ATS ecosystems and Wyloc as an AI data-security product, using SQL, Python, PostgreSQL, dbt, FastAPI, semantic matching, and production infrastructure. I’m moving to Seattle and looking for a hybrid or genuinely remote role where I can combine analytics, data engineering, automation, and technical implementation. I’m flexible on contract, contract-to-hire, or direct hire.</p></div></section></div>
  <section className="card positioning"><div className="card-head"><div><span>Three positioning variants</span><h3>Match the desk</h3></div></div><p><b>Data / analytics & BI:</b> Production-minded analyst who turns fragmented operational data into reliable SQL/PostgreSQL pipelines, BI-ready models, and decision systems; adds workflow automation where reporting alone is insufficient.</p><p><b>Data engineering & automation:</b> Builder of production SQL/Python pipelines, PostgreSQL systems, dbt models, FastAPI services, and automated workflows, demonstrated through a multi-ATS labor-market platform.</p><p><b>Applied AI & technical product systems:</b> Product-oriented builder who has shipped semantic matching and an AI data-security product, with the infrastructure and API experience to move applied-AI workflows into production.</p></section>
 </div>
}
